{
  "swagger": "2.0",
  "info": {
    "title": "LexisNexis Api Documentation",
    "version": "1.0.0"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "tags": [
    {
      "name": "Domestic",
      "description": "For Domestic Applicants"
    },
    {
      "name": "International",
      "description": "For Foreign Applicants"
    }
  ],
  "paths": {
    "/restws/identity/v3/accounts/{accountId}/workflows/WF_Gooding_and_Company.Scoring_Domestic_STG/conversations": {
      "parameters": [
        {
          "name": "Authorization",
          "in": "header",
          "description": "Basic R29vZGluZ19hbmRfQ29tcGFueV9CMkJfU1RHOlNhbGVzZm9yY2Ux\n",
          "required": true,
          "type": "string"
        },
        {
          "name": "accountId",
          "in": "path",
          "description": "'55829'\n",
          "required": true,
          "type": "string"
        },
        {
          "in": "body",
          "name": "body",
          "description": "Applicant's information that needs to be sent to LexisNexis in order to verify Instant Id and Fraud Point",
          "required": true,
          "schema": {
            "$ref": "#/definitions/Pet"
          }
        }
      ],
      "post": {
        "tags": [
          "Domestic"
        ],
        "summary": "Instant ID, Fraud Point",
        "operationId": "InstantId_FraudpointId",
        "description": "Lists floating IP addresses associated with the tenant or account.\n",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "200 OK",
            "examples": {
              "application/json": {
                "Status": {
                  "ConversationId": "31000304259759",
                  "RequestId": "572758329",
                  "TransactionStatus": "passed",
                  "TransactionReasonCode": {
                    "Code": "fraud_point_pass",
                    "Description": "FRAUD POINT PASS"
                  },
                  "Reference": "string"
                },
                "Products": [
                  {
                    "ProductType": "InstantID",
                    "ExecutedStepName": "Instant ID Step",
                    "ProductConfigurationName": "Gooding_and_Company.InstantID_STG",
                    "ProductStatus": "pass",
                    "ParameterDetails": [
                      {
                        "Group": "INSTANT_ID",
                        "Name": "LexID",
                        "Values": [
                          {
                            "Value": "385123599"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_FirstName",
                        "Values": [
                          {
                            "Value": "LARRY"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_LastName",
                        "Values": [
                          {
                            "Value": "GREEN"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_StreetAddress1",
                        "Values": [
                          {
                            "Value": "2540 RR AUX A"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_City",
                        "Values": [
                          {
                            "Value": "CHARLTON"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_State",
                        "Values": [
                          {
                            "Value": "MA"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_Zip5",
                        "Values": [
                          {
                            "Value": "01507"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_SSN",
                        "Values": [
                          {
                            "Value": "41930xxxx"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_DOB_Year",
                        "Values": [
                          {
                            "Value": "1922"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_DOB_Month",
                        "Values": [
                          {
                            "Value": "01"
                          }
                        ]
                      },
                      {
                        "Group": "VERIFIED_INPUTS",
                        "Name": "VerifiedInput_DOB_Day",
                        "Values": [
                          {
                            "Value": "XX"
                          }
                        ]
                      },
                      {
                        "Group": "INSTANT_ID",
                        "Name": "DobVerified",
                        "Values": [
                          {
                            "Value": "0"
                          }
                        ]
                      },
                      {
                        "Group": "NAME_ADDRESS_SSN_SUMMARY",
                        "Name": "NameAddressSSNSummary",
                        "Values": [
                          {
                            "Value": "12"
                          }
                        ]
                      },
                      {
                        "Group": "NAME_ADDRESS_PHONE",
                        "Name": "NAP_Summary",
                        "Values": [
                          {
                            "Value": "6"
                          }
                        ]
                      },
                      {
                        "Group": "NAME_ADDRESS_PHONE",
                        "Name": "NAP_Type",
                        "Values": [
                          {
                            "Value": "P"
                          }
                        ]
                      },
                      {
                        "Group": "NAME_ADDRESS_PHONE",
                        "Name": "NAP_Status",
                        "Values": [
                          {
                            "Value": "C"
                          }
                        ]
                      },
                      {
                        "Group": "COMPREHENSIVE_VERIFICATION_INDEX",
                        "Name": "CVI",
                        "Values": [
                          {
                            "Value": "40"
                          }
                        ]
                      },
                      {
                        "Group": "INSTANT_ID",
                        "Name": "PassportValidated",
                        "Values": [
                          {
                            "Value": "0"
                          }
                        ]
                      },
                      {
                        "Group": "INSTANT_ID",
                        "Name": "SSNFoundForLexID",
                        "Values": [
                          {
                            "Value": "false"
                          }
                        ]
                      },
                      {
                        "Group": "INSTANT_ID",
                        "Name": "InstantIDVersion",
                        "Values": [
                          {
                            "Value": "1"
                          }
                        ]
                      },
                      {
                        "Group": "RISK_INDICATORS",
                        "Name": "RiskIndicators",
                        "Values": [
                          {
                            "Value": "48",
                            "Detail": "Unable to verify first name"
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "ProductType": "FraudPoint",
                    "ExecutedStepName": "Fraud Point Step",
                    "ProductConfigurationName": "Gooding_and_Company.FraudPoint_STG",
                    "ProductStatus": "pass",
                    "ParameterDetails": [
                      {
                        "Group": "FRAUD_POINT",
                        "Name": "LexID",
                        "Values": [
                          {
                            "Value": "3204360992"
                          }
                        ]
                      },
                      {
                        "Group": "FRAUD_POINT",
                        "Name": "Model_Name",
                        "Values": [
                          {
                            "Value": "FraudPointFP31505_0"
                          }
                        ]
                      },
                      {
                        "Group": "FRAUD_POINT",
                        "Name": "Score_Type",
                        "Values": [
                          {
                            "Value": "0 to 999"
                          }
                        ]
                      },
                      {
                        "Group": "FRAUD_POINT",
                        "Name": "Score_Value",
                        "Values": [
                          {
                            "Value": "703"
                          }
                        ]
                      },
                      {
                        "Group": "FRAUD_POINT",
                        "Name": "RiskIndicators",
                        "Values": [
                          {
                            "Value": "09",
                            "Detail": "The input phone number is a pager"
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "ProductType": "FraudPoint_Decision",
                    "ExecutedStepName": "Decision Step",
                    "ProductConfigurationName": "FRAUD_POINT_PASS",
                    "ProductStatus": "pass",
                    "ProductReason": {
                      "Code": "fraud_point_pass",
                      "Description": "FRAUD POINT PASS"
                    }
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/restws/identity/v3/accounts/{accountId}/workflows/WF_Gooding_and_Company.Auth.Domestic_STG/conversations": {
      "parameters": [
        {
          "name": "Authorization",
          "in": "header",
          "description": "Basic R29vZGluZ19hbmRfQ29tcGFueV9CMkJfU1RHOlNhbGVzZm9yY2Ux\n",
          "required": true,
          "type": "string"
        },
        {
          "name": "accountId",
          "in": "path",
          "description": "'55829'\n",
          "required": true,
          "type": "string"
        },
        {
          "in": "body",
          "name": "body",
          "description": "Pet object that needs to be added to the store",
          "required": true,
          "schema": {
            "$ref": "#/definitions/Pet"
          }
        }
      ],
      "post": {
        "tags": [
          "Domestic"
        ],
        "operationId": "DomesticOTP",
        "summary": "Domestic OTP",
        "description": "Verify OTP for domestic applicants\n",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "examples": {
              "application/json": "{\n  \"Status\": {\n    \"ConversationId\": \"31000302601599\",\n    \"RequestId\": \"570323599\",\n    \"TransactionStatus\": \"pending\",\n    \"ActionType\": \"otp\",\n    \"Reference\": \"string\"\n  },\n  \"Products\": [\n      {\n          \"ProductType\": \"OTP\",\n          \"ExecutedStepName\": \"OTP Step\",\n          \"ProductConfigurationName\": \"Gooding_and_Company.OTP_STG\",\n          \"ProductStatus\": \"pending\"\n      }\n  ]\n},"
            }
          }
        }
      }
    },
    "/restws/identity/v3/accounts/{accountId}/workflows/WF_Gooding_and_Company.Auth.Domestic_STG/conversations/{conversationId}": {
      "parameters": [
        {
          "name": "Authorization",
          "in": "header",
          "description": "Basic R29vZGluZ19hbmRfQ29tcGFueV9CMkJfU1RHOlNhbGVzZm9yY2Ux\n",
          "required": true,
          "type": "string"
        },
        {
          "name": "accountId",
          "in": "path",
          "description": "'55829'\n",
          "required": true,
          "type": "string"
        },
        {
          "name": "conversationId",
          "in": "path",
          "description": "'31000302601599'\n",
          "required": true,
          "type": "string"
        },
        {
          "in": "body",
          "name": "body",
          "description": "Passcode information that needs to be sent to LexisNexis",
          "required": true,
          "schema": {
            "$ref": "#/definitions/Pet"
          }
        }
      ],
      "put": {
        "tags": [
          "Domestic"
        ],
        "operationId": "DomesticOTPContinue",
        "summary": "Domestic OTP Continuation",
        "description": "Send received passcode as body and refer to the previous conversation through conversationId (received from the response of initiation request)\n",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "200 OK",
            "examples": {
              "application/json": "{\n  \"Status\": {\n      \"ConversationId\": \"31000304255959\",\n      \"RequestId\": \"572755359\",\n      \"TransactionStatus\": \"failed\",\n      \"TransactionReasonCode\": {\n          \"Code\": \"otp_fail_invalid_passcode\"\n      },\n      \"Reference\": \"string\"\n  },\n  \"Products\": [\n      {\n          \"ProductType\": \"OTP\",\n          \"ExecutedStepName\": \"OTP Step\",\n          \"ProductConfigurationName\": \"Gooding_and_Company.OTP_STG\",\n          \"ProductStatus\": \"fail\",\n          \"ProductReason\": {\n              \"Code\": \"otp_fail_invalid_passcode\"\n          }\n      }\n  ]\n},"
            }
          }
        }
      }
    },
    "/restws/identity/v3/accounts/{accountId}/workflows/WF_Gooding_and_Company.Scoring_Foreign_STG/conversations": {
      "parameters": [
        {
          "name": "Authorization",
          "in": "header",
          "description": "Basic R29vZGluZ19hbmRfQ29tcGFueV9CMkJfU1RHOlNhbGVzZm9yY2Ux\n",
          "required": true,
          "type": "string"
        },
        {
          "name": "accountId",
          "in": "path",
          "description": "'55829'\n",
          "required": true,
          "type": "string"
        },
        {
          "name": "body",
          "in": "body",
          "description": "Applicants information that needs to be sent to LexisNexis",
          "required": true,
          "schema": {
            "$ref": "#/definitions/Pet"
          }
        }
      ],
      "post": {
        "tags": [
          "International"
        ],
        "summary": "IVI International",
        "operationId": "IVI",
        "description": "Lists floating IP addresses associated with the tenant or account.\n",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "200 OK",
            "examples": {
              "application/json": {
                "Status": {
                  "ConversationId": "31000302862099",
                  "RequestId": "570612359",
                  "TransactionStatus": "pending",
                  "ActionType": "otp",
                  "Reference": "string"
                },
                "Products": [
                  {
                    "ProductType": "OTP",
                    "ExecutedStepName": "OTP Step",
                    "ProductConfigurationName": "Gooding_and_Company.OTP_Foreign_STG",
                    "ProductStatus": "pending"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/restws/identity/v3/accounts/{accountId}/workflows/WF_Gooding_and_Company.Auth_Foreign_STG/conversations": {
      "parameters": [
        {
          "name": "Authorization",
          "in": "header",
          "description": "Basic R29vZGluZ19hbmRfQ29tcGFueV9CMkJfU1RHOlNhbGVzZm9yY2Ux\n",
          "required": true,
          "type": "string"
        },
        {
          "name": "accountId",
          "in": "path",
          "description": "'55829'\n",
          "required": true,
          "type": "string"
        },
        {
          "in": "body",
          "name": "body",
          "description": "Pet object that needs to be added to the store",
          "required": true,
          "schema": {
            "$ref": "#/definitions/Pet"
          }
        }
      ],
      "post": {
        "tags": [
          "International"
        ],
        "summary": "Foreign Otp Initiate",
        "operationId": "ForeignOtpInitiate",
        "description": "Lists floating IP addresses associated with the tenant or account.\n",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "200 OK",
            "examples": {
              "application/json": {
                "Status": {
                  "ConversationId": "31000304271409",
                  "RequestId": "572770839",
                  "TransactionStatus": "pending",
                  "ActionType": "otp",
                  "Reference": "REST_Transaction"
                },
                "Products": [
                  {
                    "ProductType": "OTP",
                    "ExecutedStepName": "OTP Step",
                    "ProductConfigurationName": "Gooding_and_Company.OTP_Foreign_STG",
                    "ProductStatus": "pending"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/restws/identity/v3/accounts/{accountId}/workflows/WF_Gooding_and_Company.Auth_Foreign_STG/conversations/{conversationId}": {
      "parameters": [
        {
          "name": "Authorization",
          "in": "header",
          "description": "Basic R29vZGluZ19hbmRfQ29tcGFueV9CMkJfU1RHOlNhbGVzZm9yY2Ux\n",
          "required": true,
          "type": "string"
        },
        {
          "name": "accountId",
          "in": "path",
          "description": "'55829'\n",
          "required": true,
          "type": "string"
        },
        {
          "name": "conversationId",
          "in": "path",
          "description": "'31000304271909'\n",
          "required": true,
          "type": "string"
        },
        {
          "in": "body",
          "name": "body",
          "description": "Pet object that needs to be added to the store",
          "required": true,
          "schema": {
            "$ref": "#/definitions/Pet"
          }
        }
      ],
      "post": {
        "tags": [
          "International"
        ],
        "summary": "Foreign OTP Continuation",
        "operationId": "ForeignOTPContinue",
        "description": "Lists floating IP addresses associated with the tenant or account.\n",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "200 OK",
            "examples": {
              "application/json": {
                "Status": {
                  "ConversationId": "31000304271909",
                  "RequestId": "572771659",
                  "TransactionStatus": "failed",
                  "TransactionReasonCode": {
                    "Code": "otp_fail_invalid_passcode"
                  },
                  "Reference": "REST_Transaction"
                },
                "Products": [
                  {
                    "ProductType": "OTP",
                    "ExecutedStepName": "OTP Step",
                    "ProductConfigurationName": "Gooding_and_Company.OTP_Foreign_STG",
                    "ProductStatus": "fail",
                    "ProductReason": {
                      "Code": "otp_fail_invalid_passcode"
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Category": {
      "type": "object",
      "properties": {
        "Mode": {
          "type": "string",
          "example": "testing"
        },
        "Reference": {
          "type": "string",
          "example": "REST_Transaction"
        },
        "Locale": {
          "type": "string",
          "example": "en_US"
        },
        "Venue": {
          "type": "string"
        }
      },
      "xml": {
        "name": "Category"
      }
    },
    "Pet": {
      "type": "object",
      "required": [
        "name",
        "photoUrls"
      ],
      "properties": {
        "category": {
          "$ref": "#/definitions/Category"
        },
        "name": {
          "type": "string",
          "example": "doggie"
        },
        "photoUrls": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  }
}